import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gestiona Tareas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon/favicon.ico" />
      <body className={inter.className}>
        <main>{children}</main>
      </body>
    </html>
  );
}
